const fs = require('fs/promises');
const { constants } = require('fs');
const path = require('path');
const yaml = require('yaml');

const logger = require('../../../utils/logger');
const { DEFAULT, DETECTORS, CORAL_DEVICE_TYPES } = require('./constants');
const { buildCameraConfig } = require('./buildCameraConfig');
const { toRetentionDays, getRecordDaysFromConfig } = require('../utils/retention');

const YAML_CONFIG = { singleQuote: true };

/**
 * @description Remove the OpenVINO model section previously generated by
 * Gladys: it is incompatible with the EdgeTPU/CPU detectors. A custom model
 * section is preserved.
 * @param {object} loadedConfig - Parsed Frigate configuration.
 * @example
 * removeGeneratedOpenvinoModel(loadedConfig);
 */
function removeGeneratedOpenvinoModel(loadedConfig) {
  if (loadedConfig.model && JSON.stringify(loadedConfig.model) === JSON.stringify(DEFAULT.OPENVINO_MODEL)) {
    delete loadedConfig.model;
  }
}

/**
 * @description Configure Frigate container. Gladys owns the mqtt, go2rtc and
 * cameras sections of the config file; any other section added manually
 * (detectors, hardware acceleration...) is left untouched. The file is only
 * rewritten when the generated content actually differs, so the caller only
 * restarts Frigate when needed.
 * @param {string} basePathOnContainer - Gladys base path.
 * @param {object} config - Gladys Frigate stored configuration.
 * @returns {Promise} Indicates if the configuration file has been created or modified.
 * @example
 * await this.configureContainer('/var/lib/gladysassistant', {});
 */
async function configureContainer(basePathOnContainer, config) {
  logger.info('Frigate Docker container is being configured...');

  // Create configuration path (if not exists)
  const configFilepath = path.join(basePathOnContainer, DEFAULT.CONFIGURATION_PATH);
  await fs.mkdir(path.dirname(configFilepath), {
    recursive: true,
  });

  // Check if config file not already exists
  let configCreated = false;
  try {
    // eslint-disable-next-line no-bitwise
    await fs.access(configFilepath, constants.R_OK | constants.W_OK);
  } catch (e) {
    logger.info('Writing default Frigate configuration...');
    await fs.writeFile(configFilepath, yaml.stringify(DEFAULT.CONFIGURATION_CONTENT, YAML_CONFIG));
    configCreated = true;
  }

  const fileContent = (await fs.readFile(configFilepath)).toString();
  const loadedConfig = yaml.parse(fileContent) || {};

  const mqtt = loadedConfig.mqtt || {};
  mqtt.enabled = true;
  mqtt.host = DEFAULT.MQTT_HOST_FROM_CONTAINER;
  mqtt.port = config.mqttPort;
  mqtt.user = config.frigateMqttUsername;
  mqtt.password = config.frigateMqttPassword;
  loadedConfig.mqtt = mqtt;

  // Build go2rtc streams and cameras sections from Gladys devices
  // (the Gladys DB is the source of truth for these two sections).
  // Within a camera, Gladys only owns ffmpeg/detect/objects.track/record/
  // snapshots: everything configured through the Frigate UI (zones, motion
  // masks, object filters, audio...) is preserved.
  const devices = await this.gladys.device.get({ service: 'frigate' });
  const existingCameras = loadedConfig.cameras || {};
  const go2rtcStreams = {};
  const cameras = {};
  // Recording retention (days), configurable from the setup page. An explicit
  // Gladys setting wins; otherwise the days already present in the file (e.g.
  // set through the Frigate UI) are preserved, then the defaults apply
  const fileDays = getRecordDaysFromConfig(loadedConfig);
  const recordContent = {
    enabled: true,
    continuous: {
      days: toRetentionDays(
        config.recordContinuousDays,
        toRetentionDays(fileDays.continuous, DEFAULT.RECORD_CONTENT.continuous.days),
      ),
    },
    alerts: {
      retain: {
        days: toRetentionDays(
          config.recordAlertsDays,
          toRetentionDays(fileDays.alerts, DEFAULT.RECORD_CONTENT.alerts.retain.days),
        ),
      },
    },
    detections: {
      retain: {
        days: toRetentionDays(
          config.recordDetectionsDays,
          toRetentionDays(fileDays.detections, DEFAULT.RECORD_CONTENT.detections.retain.days),
        ),
      },
    },
  };
  devices.forEach((device) => {
    try {
      const { cameraName, go2rtcSource, go2rtcSubSource, cameraSection } = buildCameraConfig(device, recordContent);
      go2rtcStreams[cameraName] = [go2rtcSource];
      if (go2rtcSubSource) {
        go2rtcStreams[`${cameraName}_sub`] = [go2rtcSubSource];
      }
      const existingCamera = existingCameras[cameraName] || {};
      cameras[cameraName] = {
        ...existingCamera,
        ...cameraSection,
        objects: {
          ...existingCamera.objects,
          ...cameraSection.objects,
        },
      };
      // Gladys owns the onvif section: when it is no longer generated
      // (control credentials removed), a stale one must not be preserved
      if (!cameraSection.onvif) {
        delete cameras[cameraName].onvif;
      }
    } catch (e) {
      logger.warn(`Frigate: skipping camera ${device.external_id} - ${e}`);
    }
  });

  if (Object.keys(go2rtcStreams).length > 0) {
    loadedConfig.go2rtc = { streams: go2rtcStreams };
  } else {
    delete loadedConfig.go2rtc;
  }
  // Frigate refuses to start without a cameras section
  loadedConfig.cameras = cameras;

  // VAAPI video decoding: independent from the object detector choice,
  // only added when the section is absent (manual configs preserved)
  if (this.vaapiAvailable && !loadedConfig.ffmpeg) {
    loadedConfig.ffmpeg = DEFAULT.VAAPI_FFMPEG;
  }

  // Object detector: explicit user choice, or auto (Coral > GPU > CPU).
  // A choice requiring undetected hardware falls back to auto.
  const edgetpuDetectors =
    this.coralDeviceType === CORAL_DEVICE_TYPES.PCIE ? DEFAULT.EDGETPU_DETECTORS_PCIE : DEFAULT.EDGETPU_DETECTORS_USB;
  let detector = config.detector || DETECTORS.AUTO;
  if (
    (detector === DETECTORS.CORAL && !this.coralAvailable) ||
    (detector === DETECTORS.OPENVINO && !this.openvinoCapable)
  ) {
    logger.warn(`Frigate: detector "${detector}" requires undetected hardware, falling back to auto`);
    detector = DETECTORS.AUTO;
  }
  if (detector === DETECTORS.CORAL) {
    loadedConfig.detectors = edgetpuDetectors;
    removeGeneratedOpenvinoModel(loadedConfig);
  } else if (detector === DETECTORS.OPENVINO) {
    loadedConfig.detectors = DEFAULT.OPENVINO_DETECTORS;
    loadedConfig.model = loadedConfig.model || DEFAULT.OPENVINO_MODEL;
  } else if (detector === DETECTORS.CPU) {
    loadedConfig.detectors = DEFAULT.CPU_DETECTORS;
    removeGeneratedOpenvinoModel(loadedConfig);
  } else if (!loadedConfig.detectors) {
    // auto: only added when the section is absent, so a manual
    // configuration (custom Coral, custom model...) is never overwritten.
    // The OpenVINO GPU detector only runs on Intel GPUs: an AMD render node
    // keeps the VAAPI decoding but detection stays on CPU
    if (this.coralAvailable) {
      loadedConfig.detectors = edgetpuDetectors;
    } else if (this.openvinoCapable) {
      loadedConfig.detectors = DEFAULT.OPENVINO_DETECTORS;
      loadedConfig.model = loadedConfig.model || DEFAULT.OPENVINO_MODEL;
    }
  }

  const newContent = yaml.stringify(loadedConfig, YAML_CONFIG);
  const configChanged = newContent !== fileContent;
  if (configChanged) {
    logger.info('Writing custom Frigate configuration file...');
    await fs.writeFile(configFilepath, newContent);
  }

  return { configChanged: configCreated || configChanged };
}

module.exports = {
  configureContainer,
};
